name: CI/CD React App to Kubernetes (AWS ECR)

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1ï¸âƒ£ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2ï¸âƒ£ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3ï¸âƒ£ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4ï¸âƒ£ Build React app
      - name: Build React
        run: npm run build

      # 5ï¸âƒ£ SonarQube Scan (React)
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 6ï¸âƒ£ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-east-1   # adapte si besoin

      # 7ï¸âƒ£ Login to AWS ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 8ï¸âƒ£ Build & Push Docker Image to ECR
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: bonjourf
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # 9ï¸âƒ£ Trivy Security Scan
      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.ECR_REGISTRY }}/bonjourf:latest
          severity: HIGH,CRITICAL

      # ðŸ”Ÿ Configure kubectl (Azure K8s)
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      # 10) Update image in Kubernetes manifest
       - name: Update deployment image
         run: |
          sed -i "s|image:.*|image: public.ecr.aws/p7m4r1k4/bonjour20:latest|" k8s/deployment.yaml
       - name: Copy k8s manifests to VM master
         uses: appleboy/scp-action@v0.1.7
         with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "k8s/*"
          target: "/home/${{ secrets.SSH_USER }}/app/"
       - name: Deploy to Kubernetes via SSH
         uses: appleboy/ssh-action@v1.0.3
         with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/app
            echo "DÃ©ploiement..."
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml

     
